---
apiVersion: v1
kind: Namespace
metadata:
  name: project1
  cluster: local
  labels:
    support-group: LDAP-SUPPORT-GROUP
    contacts: project1@mail.com
spec:
  kafkaUser: toto
  connector: connector1
  topicValidator:
    validationConstraints:
      min.insync.replicas:
        validation-type: Range
        min: 2
        max: 2
      retention.ms:
        validation-type: Range
        min: 60000
        max: 604800000
      partitions:
        validation-type: Range
        min: 3
        max: 6
      replication.factor:
        validation-type: Range
        min: 3
        max: 3
      cleanup.policy:
        validation-type: ValidList
        validStrings:
          - delete
          - compact
  connectValidator:
    validationConstraints:
      key.converter:
        validation-type: NonEmptyString
      value.converter:
        validation-type: NonEmptyString
      connector.class:
        validation-type: ValidString
        validStrings:
          - io.confluent.connect.jdbc.JdbcSourceConnector
          - io.confluent.connect.jdbc.JdbcSinkConnector
          - org.apache.kafka.connect.file.FileStreamSinkConnector
    sourceValidationConstraints:
      producer.override.sasl.jaas.config:
        validation-type: NonEmptyString
    sinkValidationConstraints:
      consumer.override.sasl.jaas.config:
        validation-type: NonEmptyString
    classValidationConstraints:
      io.confluent.connect.jdbc.JdbcSinkConnector:
        db.timezone:
          validation-type: NonEmptyString
