---
apiVersion: v1
kind: RoleBinding
metadata:
  name: project1-rolebinding
  namespace: project1
spec:
  role:
    resourceTypes:
      - topics
      - connects
      - acls
    verbs:
      - GET
      - POST
      - PUT
      - DELETE
  subject:
    subjectType: GROUP
    subjectName: f4m
