---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: project1-acl-topics
  namespace: project1
spec:
  resourceType: TOPIC
  resource: project1.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: project1
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: project1-acl-connects
  namespace: project1
spec:
  resourceType: CONNECT
  resource: project1.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: project1
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: project1-acl-group1
  namespace: project1
spec:
  resourceType: GROUP
  resource: project1.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: project1
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: project1-acl-groups2
  namespace: project1
spec:
  resourceType: GROUP
  resource: connect-project1.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: project1
