micronaut:
  security:
    enabled: true
    gitlab:
      enabled: true
      url: https://gitlab.com
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"

kafka:
  bootstrap.servers: "broker:29092"
  sasl.mechanism: "SCRAM-SHA-512"
  security.protocol: "SASL_PLAINTEXT"
  sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"

ns4kafka:
  security:
    admin-group: "ns4kafka"
  managed-clusters:
    local:
      manage-users: true
      manage-acls: true
      manage-topics: true
      manage-connectors: true
      drop-unsync-acls: true
      provider: "SELF_MANAGED"
      config:
        bootstrap.servers: "broker:29092"
        sasl.mechanism: "SCRAM-SHA-512"
        security.protocol: "SASL_PLAINTEXT"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"
      schema-registry:
        url: "http://schema-registry:8081"
      connects:
        local:
          url: "http://connect:8083"
