micronaut:
  application:
    name: kafkaNs
  security:
    enabled: true
    authentication: token
    gitlab:
      enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
kafka.bootstrap.servers: localhost:9092
endpoints:
  routes:
    enabled: true
    sensitive: false