micronaut:
  application:
    name: ns4kafka
  security:
    enabled: true
    authentication: token
    gitlab:
      enabled: true
      url: https://gitlab.michelin.com
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
kafka:
  health:
    enabled: false
  bootstrap.servers: "10.136.4.221:9092"
  session.timeout.ms: 10000
  delivery.timeout.ms: 10000
  request.timeout.ms: 10000
  allow.auto.create.topics: "false"

jackson:
  serialization-inclusion: NON_ABSENT
  serialization:
    indent-output: true # Pretty-print JSON

ns4kafka:
  store:
    kafka:
      enabled: true
      topics:
        prefix: ns4kafka
        props:
          cleanup.policy: "compact"
          min.compaction.lag.ms: "0"
          max.compaction.lag.ms: "60000"
          segment.ms: "60000"

  security:
    groups:
      admin: # Creates namespaces and administer them
        - f4m/admins
      audit: # Can see everything, readonly
        - nobody