micronaut:
# BEGIN ThreadPoolOptimization
# https://docs.micronaut.io/latest/guide/#clientConfiguration
# Moves HttpClient calls to a different ThreadPool
# This is mainly for Kafka Connect calls
  netty:
    event-loops:
      default:
        num-threads: 8
      connect:
        num-threads: 4
        prefer-native-transport: true
      schema:
        num-threads: 4
        prefer-native-transport: true
  http:
    services:
      /connect-proxy:
        event-loop-group: connect
      /schema-registry-proxy:
        event-loop-group: schema

# END ThreadPoolOptimization
  application:
    name: ns4kafka
  security:
    enabled: true
    authentication: bearer
    gitlab:
      enabled: true
      url: https://gitlab.michelin.com
    ldap:
      enabled: false
#      default:
#        context:
#          server: 'ldap://ldap.forumsys.com:389'
#          managerDn: 'cn=read-only-admin,dc=example,dc=com'
#          managerPassword: 'password'
#        search:
#          base: "dc=example,dc=com"
#        groups:
#          enabled: true
#          base: "dc=example,dc=com"
    endpoints:
      introspection:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

jackson:
  serialization-inclusion: NON_ABSENT
  serialization:
    indent-output: true # Pretty-print JSON

kafka:
  health:
    enabled: false
  bootstrap.servers: "localhost:9092"
  #security.protocol: "SASL_PLAINTEXT"
  #sasl.mechanism: "SCRAM-SHA-512"
  #sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user\" password=\"password\";"
  producers:
    default:
      retries: 1
      acks: all
      request.timeout.ms: 10000
      delivery.timeout.ms: 10000
  consumers:
    default:
      session.timeout.ms: 30000

ns4kafka:
  ## AKHQ
  # This section lets ns4kafka be used as JWT Claim generator for AKHQ.
  # This will generate the required payload for AKHQ during authentication in the form :
  # {
  #   "roles": ["topic/read", "topic/data/read", ...]
  #   "attributes":
  #   {
  #   "topicsFilterRegexp": ["prefix1-.*", ...]
  #   "connectFilterRegexp": ["prefix1-.*", ...]
  #   "consumerGroupsFilterRegexp": ["prefix-1.*", "connect-prefix-1.*", ...]
  #   }
  akhq:
    # Namespace label to use to find which namespace the authenticating user belongs to
    group-label: support-group
    roles:
      - topic/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
      - connect/state/update
    # Special group which will be granted ".*" on topics, connects, and groups
    admin-group: _
    # Roles to be granted to admin group
    admin-roles:
      - topic/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
      - connect/state/update
      - users/reset-password
  security:
    admin-group: DEV
#    local-users: # Not for production use.
#      - username: admin
#        # SHA-256 password.
#        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
#        groups:
#          - "admin"
  store:
    kafka:
      enabled: true
      group-id: ns4kafka.group
      init-timeout: 60000
      topics:
        prefix: ns4kafka
        replication-factor: 1
        props:
          min.insync.replicas: 1
          cleanup.policy: "compact"
          min.compaction.lag.ms: "0"
          max.compaction.lag.ms: "604800000"
          segment.ms: "600000"
  # Logs the actions performed by users when changes are made (created/deleted/changed)
  log:
    console: # 
      enabled: true
    kafka: # 
      enabled: false
      #topic: ns4kafka.audit-log
