micronaut:
  application:
    name: kafkactl
  http:
    client:
      read-timeout: 30s
kafkactl:
  version: @version@
  config-path: ${user.home}/.kafkactl
#  api: http://localhost:8080
#  user-token: token
#  current-namespace: namespace_name

