---
apiVersion: v1
kind: Topic
metadata:
  name: project1.demo1
spec:
  replicationFactor: 1
  partitions: 3
  configs:
    min.insync.replicas: '1'
    cleanup.policy: delete
    retention.ms: '600000'
