---
apiVersion: v1
kind: Connector
metadata:
  name: project1.test
  namespace: project1
spec:
  connectCluster: local
  config:
    name: project1.test
    connector.class: org.apache.kafka.connect.file.FileStreamSinkConnector
    tasks.max: '1'
    topics: connect-test
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter: org.apache.kafka.connect.storage.StringConverter
    file: "/tmp/test.sink2.txt"
