kafkactl:
  contexts:
  - context:
      api: http://ns4kafka:8080
      namespace: myNamespace
      user-token: myGitLabToken
    name: local
  current-namespace: myNamespace
  api: http://ns4kafka:8080
  user-token: myGitLabToken
