name: Release SNAPSHOT
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.1.0'
          java: 'java11'
      - name: Install Native Image
        run: gu install native-image
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build jacocoTestReport sonarqube --info
      - name: Push ns4kafka and kafkactl
        run: ./gradlew dockerBuild api:dockerPush cli:dockerPush
      - name: Native Image for CLI
        run: ./gradlew :cli:shadowJar :cli:nativeImage
      - uses: actions/upload-artifact@v2
        with:
          name: native-image
          path: ${{ github.workspace }}/cli/build/native-image/kafkactl-*
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ${{ github.workspace }}/cli/build/libs/kafkactl-*.jar
